// Copyright 2024 Stephan Friedl. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//  This implementation is drawn from CodeInRed's tuplet component.
//      https://github.com/codeinred/tuplet

//===---------------------------------------------------------------------===//
// Boost Software License - Version 1.0 - August 17th, 2003

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//===---------------------------------------------------------------------===//

#include <CppUTest/TestHarness.h>

#include <minstdconfig.h>

#include <array>
#include <fixed_string>
#include <format>
#include <__memory_resource/memory_heap_resource_adapter.h>
#include <memory>
#include <single_block_memory_heap>
#include <vector>
#include <functional>

#include <tuple>

#define TEST_BUFFER_SIZE 65536

namespace
{
    using minstd::tuple;
    using namespace minstd::tuple_literals;

    static char buffer[TEST_BUFFER_SIZE];

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
    TEST_GROUP (TupleTests)
    {
    };
#pragma GCC diagnostic pop

    //  Test traits

    static_assert(minstd::is_empty_v<tuple<>>, "Empty tuple should be an empty type");
    static_assert(minstd::stateless_v<tuple<>>, "Empty tuple should be stateless");
    static_assert(minstd::tuple_size<tuple<>>::value == 0, "An empty tuple should have a tuple size of 0");
    static_assert(minstd::is_trivial_v<tuple<>>, "AnEmptyTupleShouldBeTrivial");
    static_assert(minstd::is_trivially_assignable_v<tuple<>, tuple<>>, "AnEmptyTupleShouldBeTrivially assignable.");
    static_assert(minstd::is_trivially_copy_assignable_v<tuple<>>, "AnEmptyTupleShouldBeTrivially assignable.");
    static_assert(minstd::is_trivially_move_assignable_v<tuple<>>, "AnEmptyTupleShouldBeTrivially assignable.");

    static_assert(apply([]
                        { return 0; }, tuple<>{}) == 0,
                  "Apply not working for empty tuple");

    TEST(TupleTests, EmptyTupleShouldBeAnEmptyType)
    {
        CHECK(minstd::is_empty_v<tuple<>>);
    }

    TEST(TupleTests, EmptyTupleShouldBeStateless)
    {
        CHECK(minstd::stateless_v<tuple<>>);
    }

    TEST(TupleTests, CallingApplyOnAnEmptyTupleRequiresNoArguments)
    {
        CHECK(apply([]
                    { return 0; }, tuple{}) == 0);
    }

    TEST(TupleTests, AnEmptyTupleShouldHaveATupleSizeOf0)
    {
        CHECK(minstd::tuple_size<tuple<>>::value == 0);
    }

    TEST(TupleTests, AnEmptyTupleShouldBeTrivial)
    {
        CHECK(minstd::is_trivial_v<tuple<>>);
    }

    TEST(TupleTests, AnEmptyTupleShouldBeTriviallyAssignable)
    {
        bool result = minstd::is_trivially_assignable_v<tuple<>, tuple<>>;

        CHECK(result);
    }

    TEST(TupleTests, AnEmptyTupleShouldBeTriviallyCopyAssignable)
    {
        CHECK(minstd::is_trivially_copy_assignable_v<tuple<>>);
    }

    TEST(TupleTests, AnEmptyTupleShouldBeTriviallyMoveAssignable)
    {
        CHECK(minstd::is_trivially_move_assignable_v<tuple<>>);
    }

    struct a
    {
        int value = 0;
    };

    struct b
    {
        int value = 0;
        b &operator=(b const &b)
        {
            value = b.value;
            return *this;
        }
        b &operator=(b &&b)
        {
            value = b.value;
            return *this;
        }
    };

    struct c
    {
        int value;
        template <class U>
        c &operator=(U &&other)
        {
            value = other.value;
            return *this;
        }
    };

    struct test_other_than
    {
        template <minstd::other_than<test_other_than> T>
        constexpr bool test(T &&)
        {
            return true;
        }

        constexpr bool test(test_other_than const &) { return false; }
        constexpr bool test(test_other_than &&) { return false; }
    };

    struct test_other_than2
    {
        template <minstd::other_than<test_other_than2> T>
        constexpr bool test(T &&)
        {
            return true;
        }

        constexpr bool test(test_other_than2 &&) { return false; }
    };

    TEST(TupleTests, OtherThanTrait)
    {
        static_assert(test_other_than{}.test(0));
        static_assert(test_other_than2{}.test(0));
        {
            auto t1 = test_other_than{};
            auto const t2 = test_other_than{};
            static_assert(!test_other_than{}.test(t1));
            static_assert(!test_other_than{}.test(t2));
            static_assert(!test_other_than{}.test(minstd::move(t1)));
        }
        {
            auto t1 = test_other_than2{};
            static_assert(!test_other_than2{}.test(minstd::move(t1)));
        }
    }

    TEST(TupleTests, OtherTraits)
    {
        using tuple_a = tuple<int, int, int>;
        using tuple_b = tuple<int, int, long>;

        tuple_a a{0, 0, 0};
        auto const a_const = a;
        tuple_b b{0, 0, 10};

        static_assert(noexcept(a = a), "Assigning a tuple to itself must be noexcept for trivial types");
        static_assert(noexcept(a = a_const), "Assigning a tuple to itself must be noexcept for trivial types");
        static_assert(noexcept(a = minstd::move(a)), "Assigning a tuple to itself must be noexcept for trivial types");

        a = b;

        static_assert(minstd::is_trivially_assignable_v<tuple_a, tuple_a &>, "A tuple should be trivially assignable to itself if the members are");
        static_assert(minstd::is_trivially_assignable_v<tuple_a, tuple_a &&>, "A tuple should be trivially assignable to itself if the members are");
        static_assert(minstd::is_trivially_assignable_v<tuple_a, tuple_a const &>, "A tuple should be trivially assignable to itself if the members are");

        static_assert(minstd::is_trivially_copyable_v<tuple_a>, "Expected tuple<int, int, int> to be trivially copyable");
        static_assert(minstd::is_default_constructible_v<tuple_a>, "Expected tuple<int, int, int> to be default constructible");
        static_assert(minstd::is_aggregate_v<tuple_a>, "Expected tuple<int, int, int> to be an aggregate");

        static_assert(minstd::is_trivially_copy_assignable_v<tuple_a>, "A tuple should be trivially assignable to itself if the members are");
        static_assert(minstd::is_trivially_copy_assignable_v<tuple_b>, "A tuple should be trivially assignable to itself if the members are");
        static_assert(minstd::is_trivially_assignable_v<tuple_b, tuple_b>, "A tuple should be trivially assignable to itself if the members are");
        static_assert(!minstd::is_trivially_assignable_v<tuple_a, tuple_b>, "A tuple should not be trivially assignable to converted tuples");
        static_assert(minstd::is_trivially_move_assignable_v<tuple_a>, "A tuple should be trivially move assignable if the members are");
        static_assert(minstd::is_trivially_move_assignable_v<tuple_b>, "A tuple should be trivially move assignable if the members are");

        static_assert(minstd::is_trivial_v<tuple_a>, "A tuple should be trivial if it's members are.");
        static_assert(minstd::is_trivial_v<tuple_b>, "A tuple should be trivial if it's members are.");
    }

    //  Functional tests

    TEST(TupleTests, TuplesContainingRefs)
    {
        {
            int a = 0;
            int b = 0;

            minstd::fixed_string<> c;

            auto tup = tuple{minstd::ref(a), minstd::ref(b), minstd::ref(c)};

            static_assert(minstd::is_same_v<minstd::tuple_element<0, decltype(tup)>::type, int &>, "Expected int& at element 0");
            static_assert(minstd::is_same_v<minstd::tuple_element<1, decltype(tup)>::type, int &>, "Expected int& at element 1");
            static_assert(minstd::is_same_v<minstd::tuple_element<2, decltype(tup)>::type, minstd::fixed_string<> &>, "Expected minstd::string& at element 2");

            using minstd::get;

            tup = tuple{1, 2, "Hello, world!"};

            CHECK((a == 1 && b == 2 && c == "Hello, world!"));
        }

        {
            int a = 0;
            int b = 0;

            minstd::fixed_string<> c;

            CHECK((a == 0 && b == 0 && c == ""));

            auto tup = minstd::tie(a, b, c);

            static_assert(minstd::is_same_v<minstd::tuple_element<0, decltype(tup)>::type, int &>, "Expected int& at element 0");
            static_assert(minstd::is_same_v<minstd::tuple_element<1, decltype(tup)>::type, int &>, "Expected int& at element 1");
            static_assert(minstd::is_same_v<minstd::tuple_element<2, decltype(tup)>::type, minstd::fixed_string<> &>, "Expected minstd::string& at element 2");

            tup = tuple{1, 2, "Hello, world!"};

            CHECK((a == 1 && b == 2 && c == "Hello, world!"));
        }

        {
            int a = 0;
            int b = 0;

            minstd::fixed_string<> c;

            bool is_equal = minstd::tie(a, b, c) == minstd::tie(a, b, c);

            CHECK(is_equal);
        }

        {
            int a = 0;
            int b = 0;

            minstd::fixed_string<> c;

            bool is_equal = minstd::tie(a, b, c) == tuple{a, b, c};

            CHECK(is_equal);
        }
    }

    TEST(TupleTests, EmptyTuple)
    {
        tuple<> empty_tuple;

        static_assert(minstd::is_empty_v<tuple<>>, "Empty tuple should be an empty type");
        static_assert(minstd::stateless_v<tuple<>>, "Empty tuple should be stateless");
        static_assert(apply([]
                            { return 0; }, empty_tuple) == 0,
                      "Apply not working for empty tuple");
        static_assert(minstd::tuple_size<tuple<>>::value == 0, "An empty tuple should have a tuple size of 0");
        static_assert(minstd::is_trivial_v<tuple<>>, "AnEmptyTupleShouldBeTrivial");
        static_assert(minstd::is_trivially_assignable_v<tuple<>, tuple<>>, "AnEmptyTupleShouldBeTrivially assignable.");
        static_assert(minstd::is_trivially_copy_assignable_v<tuple<>>, "AnEmptyTupleShouldBeTrivially assignable.");
        static_assert(minstd::is_trivially_move_assignable_v<tuple<>>, "AnEmptyTupleShouldBeTrivially assignable.");

        // A tuple should be assignable from a stateless type

        empty_tuple = []() {};

        // A empty tuple should be reference assignable from a stateless type

        auto empty_lambda = []() {};
        empty_tuple = empty_lambda;

        // Checks that self-assignment compiles

        empty_tuple = empty_tuple;
    }

    TEST(TupleTests, Swap)
    {
        auto t1 = minstd::make_tuple(10, 20, minstd::fixed_string("Hello"));
        auto t2 = minstd::make_tuple(5, -129837, minstd::fixed_string("The quick brown fox jumps over the lazy dogs"));

        CHECK(minstd::get<0>(t1) == 10);
        CHECK(minstd::get<1>(t1) == 20);
        CHECK(minstd::get<2>(t1) == "Hello");

        CHECK(minstd::get<0>(t2) == 5);
        CHECK(minstd::get<1>(t2) == -129837);
        CHECK(minstd::get<2>(t2) == minstd::fixed_string("The quick brown fox jumps over the lazy dogs"));

        t1.swap(t2);

        CHECK(minstd::get<0>(t2) == 10);
        CHECK(minstd::get<1>(t2) == 20);
        CHECK(minstd::get<2>(t2) == "Hello");

        CHECK(minstd::get<0>(t1) == 5);
        CHECK(minstd::get<1>(t1) == -129837);
        CHECK(minstd::get<2>(t1) == minstd::fixed_string("The quick brown fox jumps over the lazy dogs"));

        swap(t1, t2);

        CHECK(minstd::get<0>(t1) == 10);
        CHECK(minstd::get<1>(t1) == 20);
        CHECK(minstd::get<2>(t1) == "Hello");

        CHECK(minstd::get<0>(t2) == 5);
        CHECK(minstd::get<1>(t2) == -129837);
        CHECK(minstd::get<2>(t2) == minstd::fixed_string("The quick brown fox jumps over the lazy dogs"));
    }

    TEST(TupleTests, AllMethod)
    {
        auto tup = tuple{1, 2, 3, 4.3, 5};
        CHECK(tup.all([](auto val)
                      { return val < 10; }));
        CHECK(!tup.all([](auto val)
                       { return val < 4; }));
    }

    TEST(TupleTests, AllMethodWithMove)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup = tuple{minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(10), test_heap_resource),
                         minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(20), test_heap_resource),
                         minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(30), test_heap_resource)};

        auto is_valid_ref = [](auto &value)
        { return bool(value); };

        auto is_valid_move = [](auto value)
        { return bool(value); };

        CHECK(tup.all(is_valid_ref));
        CHECK(minstd::move(tup).all(is_valid_move));
        CHECK(!tup.all(is_valid_ref));
    }

    TEST(TupleTests, AnyMethod)
    {
        auto tup = tuple{1, 2, 3, 4.3, 5};
        CHECK(tup.any([](auto val)
                      { return val < 10; }));
        CHECK(tup.any([](auto val)
                      { return val < 4; }));
        CHECK(!tup.any([](auto val)
                       { return val < 0; }));
    }

    TEST(TupleTests, AnyMethodWithMove)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup = tuple{minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(10), test_heap_resource),
                         minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(20), test_heap_resource)};

        auto is_valid_ref = [](auto &value)
        { return bool(value); };
        auto is_valid_move = [](auto value)
        { return bool(value); };

        CHECK(tup.all(is_valid_ref));
        CHECK(minstd::move(tup).any(is_valid_move));
        CHECK(tup.any(is_valid_ref));
        CHECK(minstd::move(tup).any(is_valid_move));
        CHECK(!tup.any(is_valid_ref));
    }

    TEST(TupleTests, ApplyMethod)
    {
        int a = 0;
        int b = 0;
        minstd::fixed_string<64> c;

        CHECK((a == 0 && b == 0 && c == ""));

        auto func = [](auto &x, auto &y, auto &z)
        {
            x = 1;
            y = 2;
            z = "Hello, world!";
        };

        minstd::apply(func, minstd::tie(a, b, c));

        CHECK(a == 1);
        CHECK(b == 2);
        CHECK(c == "Hello, world!");
    }

    TEST(TupleTests, ApplyMethod2)
    {
        int a = 0;
        int b = 0;
        minstd::fixed_string<64> c;

        CHECK((a == 0 && b == 0 && c == ""));

        auto func = [](auto &x, auto &y, auto &z)
        {
            x = 1;
            y = 2;
            z = "Hello, world!";
        };

        minstd::tie(a, b, c).apply(func);

        CHECK(a == 1);
        CHECK(b == 2);
        CHECK(c == "Hello, world!");
    }

    TEST(TupleTests, Assign1)
    {
        int a = -1;
        minstd::tie(a) = minstd::make_tuple(123);
        CHECK(a == 123);
    }

    TEST(TupleTests, Assign2)
    {
        int a = 0;
        int b = 0;
        minstd::fixed_string<64> c;

        minstd::tie(a, b, c).assign(1, 2, "Hello, world!");

        CHECK(a == 1);
        CHECK(b == 2);
        CHECK(c == "Hello, world!");
    }

    TEST(TupleTests, Assign3)
    {
        int a = 0;
        int b = 0;
        minstd::fixed_string<64> c;

        minstd::tie(a, b, c) = tuple{1, 2, minstd::fixed_string<64>("Hello, world!")};

        CHECK(a == 1);
        CHECK(b == 2);
        CHECK(c == "Hello, world!");
    }

    TEST(TupleTests, Assign4)
    {
        int a = 0;
        int b = 0;
        minstd::fixed_string<64> c;

        minstd::tie(a, b, c) = tuple{1, 2, "Hello, world!"};

        CHECK(a == 1);
        CHECK(b == 2);
        CHECK(c == "Hello, world!");
    }

    TEST(TupleTests, Assign5)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        tuple<minstd::unique_ptr<int>, minstd::fixed_string<64>> t, q;

        t = {minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(69420), test_heap_resource), "Hello, world!"};

        q = minstd::move(t);

        CHECK(t[0_tag].get() == nullptr);
        CHECK(*q[0_tag] == 69420);
        CHECK(q[1_tag] == "Hello, world!");
    }
    /*
    //  No shared pointers in minstd
        TEST(TupleTests, Assign6)
        {
            minstd::shared_ptr<int> p;
            minstd::fixed_string<64> s;
            tuple<minstd::shared_ptr<int>, minstd::fixed_string<64>> t, q;

            t = {minstd::make_shared<int>(69420), "Hello, world!"};

            minstd::tie(p, s) = minstd::move(t);

            CHECK(t[0_tag].get() == nullptr);
            CHECK(*p == 69420);
            CHECK(s == "Hello, world!");
        }
    */
    TEST(TupleTests, Assign7)
    {
        tuple<int, int, minstd::fixed_string<64>> t1{1, 2, "Hello, world!"}, t2;

        t2 = t1;

        CHECK(t2[0_tag] == 1);
        CHECK(t2[1_tag] == 2);
        CHECK(t2[2_tag] == "Hello, world!");
    }

    TEST(TupleTests, Assign8)
    {
        tuple<> empty_tuple;

        // A tuple should be assignable from a stateless type
        empty_tuple = [] {};

        // A empty tuple should be reference assignable from a stateless type
        auto empty_lambda = [] {};
        empty_tuple = empty_lambda;

        // Checks that self-assignment compiles
        empty_tuple = empty_tuple;
    }

    TEST(TupleTests, Assign9)
    {
        tuple<int, tuple<int>> t;

        t.assign(1, minstd::make_tuple(2));

        bool are_equal = t == tuple{1, tuple{2}};

        CHECK(are_equal);
    }

    TEST(TupleTests, Assign10)
    {
        tuple<int, tuple<double>, tuple<int>> t;

        t.assign(1, minstd::make_tuple(2.0), minstd::make_tuple(3));

        CHECK(t[0_tag] == 1);
        CHECK(t[1_tag][0_tag] == 2.0);
        CHECK(t[2_tag][0_tag] == 3);
    }

    TEST(TupleTests, ConstexprCompare)
    {
        constexpr tuple t1{10, 1};
        constexpr tuple t2{10, 2};
        constexpr tuple t3{10, 2ul};

        static_assert(t1 == t1, "Tuple equality broken");
        static_assert(t1 != t2, "Tuple equality broken");
        static_assert(t1 < t2, "Tuple compare broken");
        static_assert(t2 == t3, "Tuple equality broken");
        static_assert(t1 != t3, "Tuple equality broken");
        static_assert(t1 < t3, "Tuple compare broken");
    }

    TEST(TupleTests, LexiconographicOrdering)
    {
        tuple t1{0, 0};
        tuple t2{0, 1};
        tuple t3{1, 0};

        CHECK(t1 == t1);
        CHECK(t1 < t2);
        CHECK(t2 < t3);
        CHECK(t1 < t3);
        CHECK(t2 > t1);
        CHECK(t3 > t2);
        CHECK(t3 > t1);

        CHECK(t1 <= t2);
        CHECK(t2 <= t3);
        CHECK(t3 >= t1);
        CHECK(t2 >= t1);
        CHECK(t3 >= t2);
        CHECK(t3 >= t1);
    }
    /*
    //  string_views not in minstdlib
        TEST(TupleTests, LexiconographicOrdering2)
        {
                using namespace minstd::fixed_string<64>_view_literals;

            static_assert(minstd::sfinae::detail::_test_m_compare<minstd::fixed_string<64>_view, minstd::fixed_string<64>_view>(0));

            auto t1 = tuple{"0"sv, "0"sv};
            auto t2 = tuple{"0"sv, "00"sv};
            auto t3 = tuple{"00"sv, "0"sv};

            CHECK(t1 == t1);
            CHECK(t1 < t2);
            CHECK(t2 < t3);
            CHECK(t1 < t3);
            CHECK(t2 > t1);
            CHECK(t3 > t2);
            CHECK(t3 > t1);

            CHECK(t1 <= t2);
            CHECK(t2 <= t3);
            CHECK(t3 >= t1);
            CHECK(t2 >= t1);
            CHECK(t3 >= t2);
            CHECK(t3 >= t1);
        }
    */
    TEST(TupleTests, LexiconographicOrderingPairs)
    {
        using minstd::pair;

        pair t1{0, 0};
        pair t2{0, 1};
        pair t3{1, 0};

        CHECK(t1 == t1);
        CHECK(t1 < t2);
        CHECK(t2 < t3);
        CHECK(t1 < t3);
        CHECK(t2 > t1);
        CHECK(t3 > t2);
        CHECK(t3 > t1);

        CHECK(t1 <= t2);
        CHECK(t2 <= t3);
        CHECK(t3 >= t1);
        CHECK(t2 >= t1);
        CHECK(t3 >= t2);
        CHECK(t3 >= t1);
    }

    TEST(TupleTests, LexiconographicOrderingDifferentTypes)
    {
        tuple t1{0, 0};
        tuple t2{0ul, 1};
        tuple t3{1.0, 0};

        CHECK(t1 == t1);
        CHECK(t1 < t2);
        CHECK(t2 < t3);
        CHECK(t1 < t3);
        CHECK(t2 > t1);
        CHECK(t3 > t2);
        CHECK(t3 > t1);

        CHECK(t1 <= t2);
        CHECK(t2 <= t3);
        CHECK(t3 >= t1);
        CHECK(t2 >= t1);
        CHECK(t3 >= t2);
        CHECK(t3 >= t1);
    }

    TEST(TupleTests, TuplesWithDifferentTypes)
    {
        tuple t1{1, 2};
        tuple t2{'\1', '\2'};
        tuple t3{1ul, 2.0};

        CHECK(t1 == t1);
        CHECK(t1 == t2);
        CHECK(t1 == t3);
        CHECK(t2 == t3);
    }

    TEST(TupleTests, EmptyTupleEqualsItself)
    {
        CHECK(tuple{} == tuple{});
        CHECK(!(tuple{} != tuple{}));
    }

    TEST(TupleTests, TuplesCreatedWithReferences)
    {
        int a = 0, b = 1, c = 2;

        tuple t1 = {minstd::ref(a), minstd::ref(b)};
        tuple t2 = {minstd::ref(a), minstd::ref(c)};

        bool is_same = minstd::is_same_v<decltype(t1), tuple<int &, int &>>;

        CHECK(is_same);

        CHECK(t1 < t2);
        CHECK(t1 != t2);
        CHECK(!(t1 == t2));
        CHECK(!(t1 > t2));

        minstd::swap(b, c);

        CHECK(t2 < t1);
        CHECK(t1 != t2);
        CHECK(!(t1 == t2));
        CHECK(!(t2 > t1));
    }

    template <class A, class B, class = decltype(minstd::declval<A>() == minstd::declval<B>())>
    constexpr bool _sfinae_test_eq(int)
    {
        return true;
    }

    template <class A, class B, class = decltype(minstd::declval<A>() < minstd::declval<B>())>
    constexpr bool _sfinae_test_less(int)
    {
        return true;
    }

    template <class A, class B>
    constexpr bool _sfinae_test_eq(long long)
    {
        return false;
    }

    template <class A, class B>
    constexpr bool _sfinae_test_less(long long)
    {
        return false;
    }

    TEST(TupleTests, TupleComparisonSupportsSFINAE)
    {
        using minstd::type_list;

        struct uncomparable
        {
        };

        auto t1 = tuple{1, 2, 3};
        auto t2 = tuple{minstd::fixed_string<64>{"Hello"}, 2, 3};
        auto t3 = tuple{uncomparable{}, 2, 3};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
        constexpr bool result = _sfinae_test_eq<decltype(t1), decltype(t2)>(0);
#pragma GCC diagnostic pop

        static_assert(minstd::tuple_internal::sfinae::detail::_test_eq<int, int>(0) == true);
        static_assert(minstd::tuple_internal::sfinae::detail::_test_eq<int, minstd::fixed_string<64>>(0) == false);
        static_assert(minstd::tuple_internal::sfinae::detail::_test_eq<int, const char *>(0) == false);

        static_assert(_sfinae_test_eq<tuple<int>, tuple<const char *>>(0) == false);

        static_assert(_sfinae_test_eq<decltype(t1), decltype(t1)>(0));
        static_assert(_sfinae_test_less<decltype(t1), decltype(t1)>(0));
        static_assert(_sfinae_test_eq<decltype(t2), decltype(t2)>(0));
        static_assert(_sfinae_test_less<decltype(t2), decltype(t2)>(0));

        static_assert(!_sfinae_test_eq<decltype(t1), int>(0));
        static_assert(!_sfinae_test_less<decltype(t1), int>(0));
        static_assert(!_sfinae_test_eq<int, decltype(t1)>(0));
        static_assert(!_sfinae_test_less<int, decltype(t1)>(0));
        static_assert(!_sfinae_test_eq<decltype(t1), decltype(t2)>(0));
        static_assert(!_sfinae_test_less<decltype(t1), decltype(t2)>(0));
        static_assert(!_sfinae_test_eq<decltype(t1), decltype(t3)>(0));
        static_assert(!_sfinae_test_less<decltype(t1), decltype(t3)>(0));
        static_assert(!_sfinae_test_eq<decltype(t3), decltype(t2)>(0));
        static_assert(!_sfinae_test_less<decltype(t3), decltype(t2)>(0));

        auto t_short = tuple{1};
        auto t_long = tuple{1, 2};

        static_assert(!_sfinae_test_less<decltype(t_short), decltype(t_long)>(0));
        static_assert(!_sfinae_test_eq<decltype(t1), int>(0));
        static_assert(!_sfinae_test_less<decltype(t1), int>(0));
    }

    TEST(TupleTests, TupleConversionToReferences)
    {
        auto tup1 = tuple{0, 0, minstd::fixed_string<64>()};

        tuple<int &, int &, minstd::string &> tup2 = minstd::convert{tup1};

        tup1[0_tag] = 1;
        tup1[1_tag] = 2;
        tup1[2_tag] = "Hello, world!";

        bool is_equal = (tup2 == tuple{1, 2, "Hello, world!"});

        CHECK(is_equal);
    }

    TEST(TupleTests, TupleConversionToStruct)
    {
        struct vals
        {
            int a;
            int b;

            minstd::fixed_string<64> c;
        };

        auto tup1 = tuple{1, 2, minstd::fixed_string<64>("Hello, world!")};

        vals val = minstd::convert{tup1};

        CHECK(val.a == 1);
        CHECK(val.b == 2);
        CHECK(val.c == "Hello, world!");
    }

    TEST(TupleTests, TupleConversionToStdTuple)
    {
        auto tup1 = tuple{1, 2, minstd::fixed_string<64>("Hello, world!")};

        tuple<int, int, minstd::fixed_string<64>> val = minstd::convert{tup1};

        CHECK(minstd::get<0>(val) == 1);
        CHECK(minstd::get<1>(val) == 2);
        CHECK(minstd::get<2>(val) == "Hello, world!");
    }

    TEST(TupleTests, TupleConversionToStdVector)
    {
        auto tup1 = tuple{1, 2, 3, 4, 5};

        minstd::array<int, 5> a = minstd::convert{tup1};

        CHECK((a == minstd::array<int, 5>{1, 2, 3, 4, 5}));
    }

    TEST(TupleTests, TupleConversionResultsInMove)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup1 = tuple{1, 2, minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(3), test_heap_resource)};

        tuple<int, int, minstd::unique_ptr<int>> t2 = minstd::convert{minstd::move(tup1)};

        CHECK(minstd::get<0>(t2) == 1);
        CHECK(minstd::get<1>(t2) == 2);
        CHECK(*minstd::get<2>(t2) == 3);
    }

    TEST(TupleTests, TupleAsConversionToReferences)
    {
        auto tup1 = tuple{0, 0, minstd::fixed_string<64>()};

        auto tup2 = tup1.as<tuple<int &, int &, minstd::string &>>();

        tup1[0_tag] = 1;
        tup1[1_tag] = 2;
        tup1[2_tag] = "Hello, world!";

        bool is_equal = (tup2 == tuple{1, 2, "Hello, world!"});

        CHECK(is_equal);
    }

    TEST(TupleTests, TupleAsConversionToStruct)
    {
        struct vals
        {
            int a;
            int b;
            minstd::fixed_string<64> c;
        };

        auto tup1 = tuple{1, 2, minstd::fixed_string<64>("Hello, world!")};

        vals val = tup1.as<vals>();

        CHECK(val.a == 1);
        CHECK(val.b == 2);
        CHECK(val.c == "Hello, world!");
    }

    TEST(TupleTests, TupleAsConversionToStdTuple)
    {
        auto tup1 = tuple{1, 2, minstd::fixed_string<64>("Hello, world!")};

        auto val = tup1.as<tuple<int, int, minstd::fixed_string<64>>>();

        CHECK(minstd::get<0>(val) == 1);
        CHECK(minstd::get<1>(val) == 2);
        CHECK(minstd::get<2>(val) == "Hello, world!");
    }
    /*
    TEST(TupleTests, TupleAsConversionToStdVector) {
        auto tup1 = tuple {1, 2, 3, 4, 5};

        auto v = tup1.as<minstd::vector<int>>();

        bool is_equal = (v == minstd::vector<int> {1, 2, 3, 4, 5});

        CHECK(is_equal);
    }
    */

    TEST(TupleTests, TupleAsConversionResultsInMove)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup1 = tuple{1, 2, minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(3), test_heap_resource)};

        auto t2 = minstd::move(tup1).as<tuple<int, int, minstd::unique_ptr<int>>>();

        CHECK(minstd::get<0>(t2) == 1);
        CHECK(minstd::get<1>(t2) == 2);
        CHECK(*minstd::get<2>(t2) == 3);
    }

    TEST(TupleTests, TupleExplicitConversionToAndFromReferences)
    {
        auto tup1 = tuple{0, 0, minstd::fixed_string()};

        tuple<int &, int &, minstd::fixed_string<> &> tup2(tup1);

        tup1[0_tag] = 1;
        tup1[1_tag] = 2;
        tup1[2_tag] = "Hello, world!";

        bool is_equal = (tup2 == tuple{1, 2, minstd::fixed_string("Hello, world!")});

        CHECK(is_equal);

        tuple<int, int, minstd::fixed_string<>> tup3(tup2);

        is_equal = (tup3 == tuple<int, int, minstd::fixed_string<>>{1, 2, "Hello, world!"});

        CHECK(is_equal);
    }

    TEST(TupleTests, Testfor_each)
    {
        minstd::fixed_string<> str;

        tuple tup{
            "Hello world!",
            minstd::fixed_string<>("This is a test..."),
            10,
            'x',
            20,
            3.141592};

        tup.for_each([&](auto &value)
                     { minstd::fixed_string<> temp; minstd::format(temp, "{}\n", value); str += temp; });

        CHECK(
            str == "Hello world!\n"      //
                   "This is a test...\n" //
                   "10\n"                //
                   "x\n"                 //
                   "20\n"                //
                   "3.1415\n");
    }

    TEST(TupleTests, TestThatfor_eachMovesValuesWhenGivenMoved)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup1 = tuple{1, 2, minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(3), test_heap_resource)};

        auto tup = tuple{
            minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(10), test_heap_resource),
            minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(20), test_heap_resource),
            minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(30), test_heap_resource)};

        {
            CHECK(tup.all([](auto &val)
                          { return bool(val); }));
        }

        int sum = 0;
        minstd::move(tup).for_each([&](auto value)
                                   { sum += *value; });

        {
            CHECK(tup.all([](auto &val)
                          { return bool(val) == false; }));
            CHECK(sum == 60);
        }
    }

    TEST(TupleTests, InvokeMap)
    {
        using namespace minstd::literals::string_literals;

        auto tup = tuple{10, 20.4, "Hello, world"};

        auto expected = tuple{"10"s, "20.4000"s, "Hello, world"s};

        auto to_str = [](auto val)
        { minstd::fixed_string<> str;  minstd::format(str, "{}", val); return str; };

        CHECK(tup.map(to_str) == expected);
    }

    TEST(TupleTests, MapSupportsForwarding)
    {
        using namespace minstd::literals::string_literals;

        auto tup = tuple{10};

        auto t2 = tup.map([](auto &x) -> decltype(auto)
                          { return x; });

        auto t3 = tup.map([](auto &x) -> decltype(auto)
                          { return minstd::move(x); });

        static_assert(minstd::is_same_v<decltype(t2), tuple<int &>>);

        static_assert(minstd::is_same_v<decltype(t3), tuple<int &&>>);
    }

    TEST(TupleTests, MoveElementsWithTupleMap)
    {
        using minstd::get;
        using namespace minstd::string_literals;

        minstd::single_block_memory_heap test_heap(buffer, 4096);

        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup1 = tuple{1, 2, minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(3), test_heap_resource)};

        auto tup = tuple{10, 20.4, "Hello, world"s, minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(10), test_heap_resource)};

        auto expected = tuple{
            10,
            20.4,
            "Hello, world"s,
            minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(10), test_heap_resource)};

        auto fn = [](auto val)
        { return val; };

        auto result = minstd::move(tup).map(fn);

        CHECK(bool(get<3>(tup)) == false);
        CHECK(*get<3>(result) == *get<3>(expected));
    }

    TEST(TupleTests, CheckTupleDecomposition)
    {
        auto tup = tuple{1, 2, minstd::fixed_string("Hello, world!")};

        auto [a, b, c] = tup;

        CHECK(a == 1);
        CHECK(b == 2);
        CHECK(c == "Hello, world!");
    }

    TEST(TupleTests, CheckTupleDecompositionByReference)
    {
        using minstd::get;

        auto tup = tuple{0, 0, minstd::fixed_string()};

        auto &[a, b, c] = tup;

        a = 1;
        b = 2;
        c = "Hello, world!";

        CHECK(get<0>(tup) == 1);
        CHECK(get<1>(tup) == 2);
        CHECK(get<2>(tup) == "Hello, world!");
    }

    TEST(TupleTests, CheckTupleDecompositionByMove)
    {
        minstd::single_block_memory_heap test_heap(buffer, 4096);
        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        auto tup = tuple{
            1,
            minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(2), test_heap_resource),
            minstd::fixed_string("Hello, world!")};

        // Check that moving a tuple moves the elements when
        // doing a structured bind
        auto [a, b, c] = minstd::move(tup);

        CHECK(a == 1);
        CHECK(*b == 2);
        CHECK(c == "Hello, world!");
    }

    //  Concatenation of tuples

    static_assert(minstd::is_same_v<decltype(minstd::tuple_cat()), tuple<>>, "minstd::tuple_cat broken");
    static_assert(minstd::is_same_v<decltype(minstd::tuple_cat(tuple<>())), tuple<>>, "minstd::tuple_cat broken");
    static_assert(minstd::is_same_v<decltype(minstd::tuple_cat(tuple<int>())), tuple<int>>, "minstd::tuple_cat broken");
    static_assert(minstd::is_same_v<decltype(minstd::tuple_cat(tuple<int, char>())), tuple<int, char>>, "minstd::tuple_cat broken");
    static_assert(minstd::is_same_v<decltype(minstd::tuple_cat(tuple<char>(), tuple<int>())), tuple<char, int>>, "minstd::tuple_cat broken");
    static_assert(minstd::is_same_v<decltype(minstd::tuple_cat(tuple<char>(), tuple<int>(), tuple<minstd::fixed_string<>>())), tuple<char, int, minstd::fixed_string<>>>, "minstd::tuple_cat broken");

    TEST(TupleTests, Cat)
    {

        minstd::single_block_memory_heap test_heap(buffer, 4096);

        minstd::pmr::memory_heap_resource_adapter test_heap_resource(test_heap);

        tuple<minstd::unique_ptr<int>, minstd::fixed_string<>, char, char, char>
            tup = minstd::tuple_cat(
                tuple{minstd::unique_ptr<int>(new (test_heap_resource.allocate(sizeof(int), alignof(int))) int(69420), test_heap_resource)},
                tuple{minstd::fixed_string<>{"Hello, world!"}},
                tuple{'a', 'b', 'c'});

        CHECK(*tup[0_tag] == 69420);
        CHECK(tup[1_tag] == "Hello, world!");
        CHECK(tup[2_tag] == 'a');
        CHECK(tup[3_tag] == 'b');
        CHECK(tup[4_tag] == 'c');
    }
}
